# Cargo.toml (最终无重复版)

[package]
name = "my_overlay_handler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

# 这是构建时需要的依赖，只保留这一次
[build-dependencies]
winres = "0.1"

[dependencies]
# 我们依然需要 windows 库来提供所有的 Windows API 函数和类型
windows = { version = "0.52.0", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_System_Registry",
    "Win32_System_SystemServices",
    "Win32_System_Ole",
]}

# 我们在这里显式地、直接地依赖 windows-core 库，并强制开启它的 "macros" 功能
windows-core = { version = "0.52.0", features = ["macros"] }