# Cargo.toml (最终升级版)

[package]
name = "my_overlay_handler"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
winres = "0.1"

[dependencies]
# 我们升级到一个更新、更稳定的版本，并且在新版本中，'macros' 功能被明确地加回来了！
windows = { version = "0.58.0", features = [
    "macros",
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_System_Registry",
    "Win32_System_SystemServices",
    "Win32_System_Ole",
]}