[package]
name = "my_overlay_handler"
version = "0.1.0"
edition = "2021"

[lib]
# 告诉 Rust 编译器，我们要构建一个 C 语言兼容的动态链接库 (DLL)
crate-type = ["cdylib"]

[dependencies]
# 引入强大的 windows-rs 库，让我们可以轻松调用 Windows API
windows = { version = "0.52.0", features = [
    
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_Shell",
    "Win32_System_Registry",
    "Win32_System_SystemServices",
    "Win32_System_Ole",
    "Win32_Globalization",
] }

# 这是构建时需要的依赖，用来处理 Windows 资源文件（比如图标）
[build-dependencies]
winres = "0.1"