name: Build Release DLL

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust toolchain (MSVC)
      run: |
        rustup toolchain install stable-x86_64-pc-windows-msvc
        rustup default stable-x86_64-pc-windows-msvc

    - name: Add x86_64 target (just in case)
      run: rustup target add x86_64-pc-windows-msvc

    - name: Build for x86_64 (release)
      run: cargo build --release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-overlay-handler-dll
        path: target\\release\\my_overlay_handler.dll
